---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-failover-operator
  namespace: default
  labels:
    app: node-failover-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node-failover-operator
  template:
    metadata:
      labels:
        app: node-failover-operator
    spec:
      serviceAccountName: node-failover-operator

      nodeSelector:
        node-type: gcp-permanent

      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule

      priorityClassName: system-cluster-critical

      containers:
        - name: operator
          image: ghcr.io/mizuamedesu/hybrid-node-operator:latest
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: node-failover-config

          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json

          volumeMounts:
            - name: gcp-credentials
              mountPath: /var/secrets/google
              readOnly: true

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3

      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials