---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-failover-operator
  namespace: default
  labels:
    app: node-failover-operator
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: node-failover-operator
  template:
    metadata:
      labels:
        app: node-failover-operator
    spec:
      serviceAccountName: node-failover-operator

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: node-failover-operator
                topologyKey: kubernetes.io/hostname

      nodeSelector:
        node-type: gcp-permanent

      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule

      priorityClassName: system-cluster-critical

      containers:
        - name: operator
          image: ghcr.io/mizuamedesu/hybrid-node-operator:latest
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: node-failover-config

          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          volumeMounts:
            - name: gcp-credentials
              mountPath: /var/secrets/google
              readOnly: true

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3

      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials